version: 2

jobs:
  build_and_push_tag:
    machine: true
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            docker build --no-cache --build-arg APP_VERSION=$CIRCLE_TAG -t build-output -f Dockerfile.builder .
            docker create --name extract build-output
            docker cp extract:/go/src/github.com/ICTU/plumber/plumber ./plumber
            docker build -f Dockerfile.app -t ictu/plumber .
            docker tag ictu/plumber ictu/plumber:${CIRCLE_TAG}
            MAJOR_VERSION=${CIRCLE_TAG/.*}; docker tag ictu/plumber ictu/plumber:${MAJOR_VERSION}
            MINOR_VERSION=${CIRCLE_TAG%.*}; docker tag ictu/plumber ictu/plumber:${MINOR_VERSION}
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ictu/plumber
            docker push ictu/plumber:${CIRCLE_TAG}
            docker push ictu/plumber:${MINOR_VERSION}
            docker push ictu/plumber:${MAJOR_VERSION}

workflows:
  version: 2
  build_and_push:
    jobs:
      - build_and_push_tag:
          filters:
            tags:
              only: /^[0-9]+\.[0-9]+\.[0-9]+$/
            branches:
              ignore: /.*/